// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWA7Rbp16VckHNWxOs5fhwLYIgyTHRlqE',
    appId: '1:1011007104549:web:9895be97cc4c98a6bd81cc',
    messagingSenderId: '1011007104549',
    projectId: 'eatwhathelpbyvideo',
    authDomain: 'eatwhathelpbyvideo.firebaseapp.com',
    storageBucket: 'eatwhathelpbyvideo.appspot.com',
    measurementId: 'G-QD0M5C8KDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAglr9GlPr1daZjCCONvwCZiwG3dOyfZXE',
    appId: '1:1011007104549:android:4dc58a969bb3a1dabd81cc',
    messagingSenderId: '1011007104549',
    projectId: 'eatwhathelpbyvideo',
    storageBucket: 'eatwhathelpbyvideo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJtyxVmzsjwoRUWWlNrsAetLZsc4aAtuI',
    appId: '1:1011007104549:ios:8de75cc2acf75d5fbd81cc',
    messagingSenderId: '1011007104549',
    projectId: 'eatwhathelpbyvideo',
    storageBucket: 'eatwhathelpbyvideo.appspot.com',
    iosBundleId: 'com.example.eatwhathelpbyvideo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJtyxVmzsjwoRUWWlNrsAetLZsc4aAtuI',
    appId: '1:1011007104549:ios:82bfb4ddff70430abd81cc',
    messagingSenderId: '1011007104549',
    projectId: 'eatwhathelpbyvideo',
    storageBucket: 'eatwhathelpbyvideo.appspot.com',
    iosBundleId: 'com.example.eatwhathelpbyvideo.RunnerTests',
  );
}
